env:
  browser: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
plugins:
  - html
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
